### ISSUE TITLE
[Dice Roller] Missing Animation During Dice Roll

### ISSUE THREAD

**Issue by harsSharma45** [harsSharma45/Hacktoberfest-2024#13]
**Expected Behavior:**

A smooth dice-rolling animation should be triggered each time the user rolls the dice, adding a dynamic effect to the outcome.

**Possible Solutions:**

1. Implement a CSS or JavaScript-based animation for the dice roll.
2. Ensure that the animation duration is visually appealing, but not too long to delay the result.

**Comment by Vikas350** [comment]
Hi @harsSharma45, i want to contribute to this please assign this to me.

**Comment by ShikharNigam2426** [comment]
Hello @harsSharma45 i have resolved the issue please assign this to me so i can create PR.
