### ISSUE TITLE
Improve Accessibility

### ISSUE THREAD

**Issue by harsSharma45** [harsSharma45/Hacktoberfest-2024#3]
Improve accessibility features in the app to ensure it is usable for people with disabilities, including proper labeling and keyboard navigation

**Comment by nobledeveloper01** [comment]
Pls assign me to this, i hope i am just adding accessibility to what we have currently

**Comment by ShikharNigam2426** [comment]
i have solved this issue and raised the pr for this issue, please review it.

**Comment by harsSharma45** [comment]
@ShikharNigam2426 Share the link to your pull request so I can review it.

**Comment by ShikharNigam2426** [comment]
@harsSharma45 https://github.com/harsSharma45/Hacktoberfest-2024/pull/28
